"""Initial migration

Revision ID: 7438c50d8aed
Revises: 
Create Date: 2023-08-06 19:20:19.850522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7438c50d8aed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linecount', sa.Integer(), nullable=True))
    with op.batch_alter_table('poem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linecount', sa.Integer(), nullable=True, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poem', schema=None) as batch_op:
        batch_op.drop_column('linecount')

    # ### end Alembic commands ###
